server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 127.0.0.1:9000
    timeout: 10s
data:
  database:
    driver: mysql
    source: root:a111111@tcp(127.0.0.1:3306)/qs_mall_pms?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
